# config/packages/imgproxy.yaml
imgproxy:
    host: '%env(IMGPROXY_HOST)%'
    signature:
        key: '%env(IMGPROXY_KEY)%'
        salt: '%env(IMGPROXY_SALT)%'
    media_url: https://media.localhost

    # default settings applied for all presets
    default_preset_settings:
        format: webp
        encode: true

    presets:
        # this is a preset example
        tiny:
            format: png
            options:
                resize:
                    # fit, fill, auto|scale,min-fit
                    resizing_type: auto
                    width: 150
                    height: 75
                    enlarge: true

        png_thumbnail:
            format: png
            options:
                resize:
                    resizing_type: fit
                    width: 150
                    height: 75
                    enlarge: true
                    extend:
                        extend: true
                        gravity:
                            type: no
                            x_offset: 10
                            y_offset: 10
                rotate:
                    angle: 90
