FROM docker.io/python:3.12-slim

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    imagemagick \
    libzbar0 \
    zbar-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    flask \
    opencv-python-headless \
    opencv-contrib-python-headless \
    numpy \
    pillow \
    wand \
    pyzbar

WORKDIR /app
COPY opencv-server.py /app/server.py

EXPOSE 8885
CMD ["python", "server.py"]
