<?php

namespace App\Controller\Admin;

use App\Entity\File;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Survos\CoreBundle\Entity\RouteParametersInterface;
use Survos\EzBundle\Controller\AbstractEzCrudController;
use Survos\EzBundle\Field\LinkedTextField;

/**
 * Generated by code:meili:admin
 */
final class FileCrudController extends AbstractEzCrudController
{
    /** TODO: adjust SHOW_ROUTE to your app show route */
    public const SHOW_ROUTE = 'admin_app_file_show';

    public static function getEntityFqcn(): string
    {
        return \App\Entity\File::class;
    }

    protected function preferredFields(string $pageName): iterable
    {
        if ($pageName !== Crud::PAGE_INDEX) {
            return [];
        }

        yield TextField::new('marking');
    }
}
