<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603102510 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dataset_artifact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, code VARCHAR(128) NOT NULL, uri VARCHAR(1024) DEFAULT NULL, size_bytes INT DEFAULT NULL, row_count INT DEFAULT NULL, checksum VARCHAR(128) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, discovered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dto_counts JSON DEFAULT NULL, metadata JSONB NOT NULL, dataset_key VARCHAR(128) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D77156A56BF576FB ON dataset_artifact (dataset_key)');
        $this->addSql('CREATE INDEX IDX_D77156A58CDE5729 ON dataset_artifact (type)');
        $this->addSql('CREATE INDEX IDX_D77156A577153098 ON dataset_artifact (code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_dataset_artifact ON dataset_artifact (dataset_key, type, code)');
        $this->addSql('CREATE TABLE fetch_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, page_number INT NOT NULL, url VARCHAR(2048) NOT NULL, status VARCHAR(32) NOT NULL, content_type VARCHAR(255) DEFAULT NULL, accept VARCHAR(255) DEFAULT NULL, archive_path VARCHAR(2048) DEFAULT NULL, record_count INT DEFAULT NULL, error VARCHAR(1024) DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_page ON fetch_page (provider_code, dataset_key, kind, page_number)');
        $this->addSql('CREATE TABLE fetch_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, row_number INT NOT NULL, source_id VARCHAR(255) DEFAULT NULL, record_type VARCHAR(32) DEFAULT NULL, payload TEXT NOT NULL, payload_bytes INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fetch_page_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FB10B11C9F2FB857 ON fetch_record (fetch_page_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_record_page_row ON fetch_record (fetch_page_id, row_number)');
        $this->addSql('ALTER TABLE dataset_artifact ADD CONSTRAINT FK_D77156A56BF576FB FOREIGN KEY (dataset_key) REFERENCES dataset_info (dataset_key) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fetch_record ADD CONSTRAINT FK_FB10B11C9F2FB857 FOREIGN KEY (fetch_page_id) REFERENCES fetch_page (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dataset_info DROP pixie_db_path');
        $this->addSql('ALTER TABLE dataset_info DROP pixie_row_count');
        $this->addSql('ALTER INDEX uniq_c76484f1a66100bb RENAME TO UNIQ_274D054FE8BF7264');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA toolkit_experimental');
        $this->addSql('CREATE SCHEMA timescaledb_information');
        $this->addSql('CREATE SCHEMA timescaledb_experimental');
        $this->addSql('CREATE SCHEMA _timescaledb_internal');
        $this->addSql('CREATE SCHEMA _timescaledb_functions');
        $this->addSql('CREATE SCHEMA _timescaledb_config');
        $this->addSql('CREATE SCHEMA _timescaledb_catalog');
        $this->addSql('CREATE SCHEMA _timescaledb_cache');
        $this->addSql('ALTER TABLE dataset_artifact DROP CONSTRAINT FK_D77156A56BF576FB');
        $this->addSql('ALTER TABLE fetch_record DROP CONSTRAINT FK_FB10B11C9F2FB857');
        $this->addSql('DROP TABLE dataset_artifact');
        $this->addSql('DROP TABLE fetch_page');
        $this->addSql('DROP TABLE fetch_record');
        $this->addSql('ALTER TABLE dataset_info ADD pixie_db_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dataset_info ADD pixie_row_count INT DEFAULT NULL');
        $this->addSql('ALTER INDEX uniq_274d054fe8bf7264 RENAME TO uniq_c76484f1a66100bb');
    }
}
