<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260113205417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id VARCHAR(16) NOT NULL, status_code INT DEFAULT NULL, mime VARCHAR(255) DEFAULT NULL, size BIGINT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, context JSON DEFAULT NULL, clients JSON NOT NULL, storage_backend TEXT DEFAULT NULL, storage_key TEXT DEFAULT NULL, archive_url TEXT DEFAULT NULL, temp_filename TEXT DEFAULT NULL, ext VARCHAR(12) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, original_url TEXT NOT NULL, marking VARCHAR(32) DEFAULT NULL, local_dir_id VARCHAR(3) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF5A5CE9C1AF63 ON asset (local_dir_id)');
        $this->addSql('CREATE INDEX idx_asset_created_at ON asset (created_at)');
        $this->addSql('CREATE INDEX idx_asset_mime ON asset (mime)');
        $this->addSql('CREATE INDEX idx_asset_backend ON asset (storage_backend)');
        $this->addSql('CREATE TABLE asset_path (id VARCHAR(3) NOT NULL, files INT NOT NULL, bytes INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, asset_meta JSONB DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_storage_files ON asset_path (files)');
        $this->addSql('CREATE TABLE asset_variant (id VARCHAR(255) NOT NULL, preset VARCHAR(64) NOT NULL, format VARCHAR(12) NOT NULL, size BIGINT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, quality SMALLINT DEFAULT NULL, storage_backend TEXT DEFAULT NULL, storage_key TEXT DEFAULT NULL, url TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, marking VARCHAR(32) DEFAULT NULL, asset_id VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92ADFEFB5DA1941 ON asset_variant (asset_id)');
        $this->addSql('CREATE INDEX idx_variant_preset ON asset_variant (preset)');
        $this->addSql('CREATE INDEX idx_variant_format ON asset_variant (format)');
        $this->addSql('CREATE INDEX idx_variant_created_at ON asset_variant (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_asset_preset_format ON asset_variant (asset_id, preset, format)');
        $this->addSql('CREATE TABLE babel_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, path VARCHAR(512) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, sort INT DEFAULT NULL, term_set_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77FE42F2F3AD3475 ON babel_term (term_set_id)');
        $this->addSql('CREATE INDEX IDX_77FE42F2727ACA70 ON babel_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_code_uq ON babel_term (term_set_id, code)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_path_uq ON babel_term (term_set_id, path)');
        $this->addSql('CREATE TABLE file (id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, last_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_size INT DEFAULT NULL, dir_count INT DEFAULT NULL, file_count INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, is_dir BOOLEAN NOT NULL, is_public BOOLEAN NOT NULL, child_count INT NOT NULL, lvl INT NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, marking VARCHAR(32) DEFAULT NULL, storage_id VARCHAR(255) NOT NULL, parent_id VARCHAR DEFAULT NULL, root_id VARCHAR DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C9F36105CC5DB90 ON file (storage_id)');
        $this->addSql('CREATE INDEX IDX_8C9F3610727ACA70 ON file (parent_id)');
        $this->addSql('CREATE INDEX IDX_8C9F361079066886 ON file (root_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STORAGE_PATH ON file (storage_id, path)');
        $this->addSql('CREATE TABLE index_info (index_name VARCHAR(255) NOT NULL, locale VARCHAR(255) DEFAULT NULL, last_indexed TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_count INT NOT NULL, settings JSONB NOT NULL, task_id VARCHAR(255) DEFAULT NULL, primary_key VARCHAR(255) NOT NULL, batch_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, PRIMARY KEY (index_name))');
        $this->addSql('CREATE TABLE media (id VARCHAR(32) NOT NULL, status VARCHAR(255) NOT NULL, provider VARCHAR(100) DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, external_url TEXT DEFAULT NULL, raw_data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, thumbnail_url TEXT DEFAULT NULL, location JSON DEFAULT NULL, tags JSON NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, duration INT DEFAULT NULL, file_size BIGINT DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, title TEXT DEFAULT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, camera VARCHAR(255) DEFAULT NULL, exif_data JSON DEFAULT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, view_count INT DEFAULT NULL, like_count INT DEFAULT NULL, chapters JSON DEFAULT NULL, subtitles JSON DEFAULT NULL, artist VARCHAR(255) DEFAULT NULL, album VARCHAR(255) DEFAULT NULL, bitrate INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE processed_messages (run_id INT NOT NULL, attempt SMALLINT NOT NULL, message_type VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, dispatched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wait_time BIGINT NOT NULL, handle_time BIGINT NOT NULL, memory_usage BIGINT NOT NULL, transport VARCHAR(255) NOT NULL, tags VARCHAR(255) DEFAULT NULL, failure_type VARCHAR(255) DEFAULT NULL, failure_message TEXT DEFAULT NULL, results JSON DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE storage (adapter VARCHAR(255) DEFAULT NULL, root VARCHAR(255) DEFAULT NULL, id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE str (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, source_locale VARCHAR(10) NOT NULL, source TEXT NOT NULL, context VARCHAR(80) DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_ctx_idx ON str (context)');
        $this->addSql('CREATE INDEX str_src_locale_idx ON str (source_locale)');
        $this->addSql('CREATE INDEX str_src_locale_ctx_idx ON str (source_locale, context)');
        $this->addSql('CREATE UNIQUE INDEX str_code_uq ON str (code)');
        $this->addSql('CREATE TABLE str_tr (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, str_code VARCHAR(64) NOT NULL, target_locale VARCHAR(10) NOT NULL, engine VARCHAR(20) DEFAULT NULL, text TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_tr_target_locale_idx ON str_tr (target_locale)');
        $this->addSql('CREATE INDEX str_tr_str_code_idx ON str_tr (str_code)');
        $this->addSql('CREATE UNIQUE INDEX str_tr_uq ON str_tr (str_code, target_locale, engine)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE term_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_set_code_uq ON term_set (code)');
        $this->addSql('CREATE TABLE users (roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, api_key VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, bin_count INT NOT NULL, id VARCHAR(255) NOT NULL, approx_image_count INT NOT NULL, media_callback_url VARCHAR(255) DEFAULT NULL, thumb_callback_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CE9C1AF63 FOREIGN KEY (local_dir_id) REFERENCES asset_path (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE asset_variant ADD CONSTRAINT FK_92ADFEFB5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2F3AD3475 FOREIGN KEY (term_set_id) REFERENCES term_set (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2727ACA70 FOREIGN KEY (parent_id) REFERENCES babel_term (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36105CC5DB90 FOREIGN KEY (storage_id) REFERENCES storage (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F3610727ACA70 FOREIGN KEY (parent_id) REFERENCES file (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F361079066886 FOREIGN KEY (root_id) REFERENCES file (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5CE9C1AF63');
        $this->addSql('ALTER TABLE asset_variant DROP CONSTRAINT FK_92ADFEFB5DA1941');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2F3AD3475');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2727ACA70');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36105CC5DB90');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F3610727ACA70');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F361079066886');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE asset_path');
        $this->addSql('DROP TABLE asset_variant');
        $this->addSql('DROP TABLE babel_term');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE index_info');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE processed_messages');
        $this->addSql('DROP TABLE storage');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_tr');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE term_set');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
