<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250923162058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id VARCHAR(16) NOT NULL, status_code INT DEFAULT NULL, mime TEXT DEFAULT NULL, size BIGINT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, context JSON DEFAULT NULL, storage_backend TEXT DEFAULT NULL, storage_key TEXT DEFAULT NULL, temp_filename TEXT DEFAULT NULL, ext VARCHAR(12) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, original_url TEXT NOT NULL, marking VARCHAR(32) DEFAULT NULL, local_dir_id VARCHAR(3) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF5A5CE9C1AF63 ON asset (local_dir_id)');
        $this->addSql('CREATE INDEX idx_asset_created_at ON asset (created_at)');
        $this->addSql('CREATE INDEX idx_asset_mime ON asset (mime)');
        $this->addSql('CREATE INDEX idx_asset_backend ON asset (storage_backend)');
        $this->addSql('CREATE TABLE asset_path (id VARCHAR(3) NOT NULL, files INT NOT NULL, bytes BIGINT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, asset_meta JSONB DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_storage_files ON asset_path (files)');
        $this->addSql('CREATE TABLE asset_variant (id VARCHAR(255) NOT NULL, preset VARCHAR(64) NOT NULL, format VARCHAR(12) NOT NULL, size BIGINT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, quality SMALLINT DEFAULT NULL, storage_backend TEXT DEFAULT NULL, storage_key TEXT DEFAULT NULL, url TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, marking VARCHAR(32) DEFAULT NULL, asset_id VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92ADFEFB5DA1941 ON asset_variant (asset_id)');
        $this->addSql('CREATE INDEX idx_variant_preset ON asset_variant (preset)');
        $this->addSql('CREATE INDEX idx_variant_format ON asset_variant (format)');
        $this->addSql('CREATE INDEX idx_variant_created_at ON asset_variant (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_asset_preset_format ON asset_variant (asset_id, preset, format)');
        $this->addSql('CREATE TABLE file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, last_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_size INT DEFAULT NULL, listing_count INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, is_dir BOOLEAN NOT NULL, is_public BOOLEAN NOT NULL, child_count INT NOT NULL, lvl INT NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, marking VARCHAR(32) DEFAULT NULL, storage_id INT NOT NULL, parent_id INT DEFAULT NULL, root_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C9F36105CC5DB90 ON file (storage_id)');
        $this->addSql('CREATE INDEX IDX_8C9F3610727ACA70 ON file (parent_id)');
        $this->addSql('CREATE INDEX IDX_8C9F361079066886 ON file (root_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STORAGE_PATH ON file (storage_id, path)');
        $this->addSql('CREATE TABLE index_info (index_name VARCHAR(255) NOT NULL, pixie_code VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, last_indexed TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_count INT NOT NULL, task_id VARCHAR(255) DEFAULT NULL, batch_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, PRIMARY KEY (index_name))');
        $this->addSql('CREATE TABLE key_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX kv_type_value ON key_value (type, value)');
        $this->addSql('CREATE TABLE media (mime_type VARCHAR(255) DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, colors JSON DEFAULT NULL, color_analysis JSONB DEFAULT NULL, perceptual_hash VARCHAR(16) DEFAULT NULL, temp_filename VARCHAR(255) DEFAULT NULL, size INT DEFAULT NULL, resized JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, blur VARCHAR(255) DEFAULT NULL, status_code INT DEFAULT NULL, original_height INT DEFAULT NULL, original_width INT DEFAULT NULL, ext VARCHAR(4) DEFAULT NULL, exif JSONB DEFAULT NULL, context JSON DEFAULT NULL, code VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, original_url TEXT DEFAULT NULL, description_backing TEXT DEFAULT NULL, caption_backing TEXT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, user_id VARCHAR(255) NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE INDEX IDX_6A2CA10CA76ED395 ON media (user_id)');
        $this->addSql('CREATE INDEX media_status_code_index ON media (status_code)');
        $this->addSql('CREATE INDEX media_size ON media (size)');
        $this->addSql('CREATE TABLE processed_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE storage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, adapter VARCHAR(255) DEFAULT NULL, root VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE str (hash VARCHAR(64) NOT NULL, original TEXT NOT NULL, src_locale VARCHAR(8) NOT NULL, context VARCHAR(128) DEFAULT NULL, meta JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT NULL, locale_statuses JSONB DEFAULT NULL, PRIMARY KEY (hash))');
        $this->addSql('CREATE TABLE str_translation (meta JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT NULL, hash VARCHAR(40) NOT NULL, str_hash VARCHAR(32) NOT NULL, locale VARCHAR(8) NOT NULL, text TEXT DEFAULT NULL, PRIMARY KEY (hash))');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE thumb (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, size INT DEFAULT NULL, w INT DEFAULT NULL, h INT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, liip_code VARCHAR(16) NOT NULL, marking VARCHAR(32) DEFAULT NULL, media_id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1537D1DBEA9FDD75 ON thumb (media_id)');
        $this->addSql('CREATE TABLE users (roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, api_key VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, bin_count INT NOT NULL, id VARCHAR(255) NOT NULL, approx_image_count INT NOT NULL, media_callback_url VARCHAR(255) DEFAULT NULL, thumb_callback_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CE9C1AF63 FOREIGN KEY (local_dir_id) REFERENCES asset_path (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE asset_variant ADD CONSTRAINT FK_92ADFEFB5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36105CC5DB90 FOREIGN KEY (storage_id) REFERENCES storage (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F3610727ACA70 FOREIGN KEY (parent_id) REFERENCES file (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F361079066886 FOREIGN KEY (root_id) REFERENCES file (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thumb ADD CONSTRAINT FK_1537D1DBEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (code) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5CE9C1AF63');
        $this->addSql('ALTER TABLE asset_variant DROP CONSTRAINT FK_92ADFEFB5DA1941');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36105CC5DB90');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F3610727ACA70');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F361079066886');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CA76ED395');
        $this->addSql('ALTER TABLE thumb DROP CONSTRAINT FK_1537D1DBEA9FDD75');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE asset_path');
        $this->addSql('DROP TABLE asset_variant');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE index_info');
        $this->addSql('DROP TABLE key_value');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE processed_messages');
        $this->addSql('DROP TABLE storage');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_translation');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE thumb');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
