<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708155519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE command_process (id VARCHAR(26) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, command VARCHAR(255) NOT NULL, cli TEXT DEFAULT NULL, mode VARCHAR(16) NOT NULL, host VARCHAR(128) DEFAULT NULL, pid INT DEFAULT NULL, status VARCHAR(16) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exit_code INT DEFAULT NULL, memory_bytes INT DEFAULT NULL, output TEXT DEFAULT NULL, failure_message TEXT DEFAULT NULL, slots JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_command_process_status ON command_process (status)');
        $this->addSql('CREATE INDEX idx_command_process_command ON command_process (command)');
        $this->addSql('CREATE INDEX idx_command_process_created ON command_process (created_at)');
        $this->addSql('DROP TABLE claim');
        $this->addSql('DROP TABLE claim_run');
        $this->addSql('ALTER TABLE ai_batch ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ai_batch ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE media ADD dataset VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE media ADD ai_queue JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE media ADD ai_completed JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE media ADD ai_locked BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE media ADD ai_document_type VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA toolkit_experimental');
        $this->addSql('CREATE SCHEMA timescaledb_information');
        $this->addSql('CREATE SCHEMA timescaledb_experimental');
        $this->addSql('CREATE SCHEMA _timescaledb_internal');
        $this->addSql('CREATE SCHEMA _timescaledb_functions');
        $this->addSql('CREATE SCHEMA _timescaledb_config');
        $this->addSql('CREATE SCHEMA _timescaledb_catalog');
        $this->addSql('CREATE SCHEMA _timescaledb_cache');
        $this->addSql('CREATE TABLE claim (id VARCHAR(26) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scope VARCHAR(64) DEFAULT NULL, subject_type VARCHAR(32) NOT NULL, subject_id VARCHAR(64) NOT NULL, predicate VARCHAR(64) NOT NULL, source VARCHAR(128) NOT NULL, value JSONB NOT NULL, confidence SMALLINT NOT NULL, basis TEXT DEFAULT NULL, run_id VARCHAR(26) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_claim_run ON claim (run_id)');
        $this->addSql('CREATE INDEX idx_claim_scope_subject_pred ON claim (scope, subject_type, subject_id, predicate)');
        $this->addSql('CREATE INDEX idx_claim_scope_source ON claim (scope, source)');
        $this->addSql('CREATE TABLE claim_run (id VARCHAR(26) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scope VARCHAR(64) DEFAULT NULL, subject_type VARCHAR(32) NOT NULL, subject_id VARCHAR(64) NOT NULL, source VARCHAR(128) NOT NULL, model VARCHAR(128) DEFAULT NULL, prompt TEXT DEFAULT NULL, response JSONB DEFAULT NULL, input_tokens INT DEFAULT NULL, output_tokens INT DEFAULT NULL, image_tokens INT DEFAULT NULL, duration_ms INT DEFAULT NULL, claim_count INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_claim_run_created ON claim_run (created_at)');
        $this->addSql('CREATE INDEX idx_claim_run_scope_subject_source ON claim_run (scope, subject_type, subject_id, source)');
        $this->addSql('DROP TABLE command_process');
        $this->addSql('ALTER TABLE ai_batch ALTER id SET DEFAULT nextval(\'ai_batch_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE ai_batch ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE media DROP dataset');
        $this->addSql('ALTER TABLE media DROP ai_queue');
        $this->addSql('ALTER TABLE media DROP ai_completed');
        $this->addSql('ALTER TABLE media DROP ai_locked');
        $this->addSql('ALTER TABLE media DROP ai_document_type');
    }
}
